Importing the libraries

In [2]:
import numpy as np
import pandas as pd
from pandas.core.base import value_counts
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import MaxAbsScaler

Reading the files

In [3]:
df=pd.read_csv("creditcard.csv", error_bad_lines=False)

C:\Users\PC\AppData\Local\Temp\ipykernel_13896\3088716342.py:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df=pd.read_csv("creditcard.csv", error_bad_lines=False)

In [4]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

Statistical Measure of Data

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Time,284807.0,9.481386e+04,47488.145955,0.000000,54201.500000,84692.000000,139320.500000,172792.000000
V1,284807.0,1.168375e-15,1.958696,-56.407510,-0.920373,0.018109,1.315642,2.454930
V2,284807.0,3.416908e-16,1.651309,-72.715728,-0.598550,0.065486,0.803724,22.057729
V3,284807.0,-1.379537e-15,1.516255,-48.325589,-0.890365,0.179846,1.027196,9.382558
V4,284807.0,2.074095e-15,1.415869,-5.683171,-0.848640,-0.019847,0.743341,16.875344
V5,284807.0,9.604066e-16,1.380247,-113.743307,-0.691597,-0.054336,0.611926,34.801666
V6,284807.0,1.487313e-15,1.332271,-26.160506,-0.768296,-0.274187,0.398565,73.301626
V7,284807.0,-5.556467e-16,1.237094,-43.557242,-0.554076,0.040103,0.570436,120.589494
V8,284807.0,1.213481e-16,1.194353,-73.216718,-0.208630,0.022358,0.327346,20.007208
V9,284807.0,-2.406331e-15,1.098632,-13.434066,-0.643098,-0.051429,0.597139,15.594995
V10,284807.0,2.239053e-15,1.088850,-24.588262,-0.535426,-0.092917,0.453923,23.745136
V11,284807.0,1.673327e-15,1.020713,-4.797473,-0.762494,-0.032757,0.739593,12.018913
V12,284807.0,-1.247012e-15,0.999201,-18.683715,-0.405571,0.140033,0.618238,7.848392
V13,284807.0,8.190001e-16,0.995274,-5.791881,-0.648539,-0.013568,0.662505,7.126883
V14,284807.0,1.207294e-15,0.958596,-19.214325,-0.425574,0.050601,0.493150,10.526766
V15,284807.0,4.887456e-15,0.915316,-4.498945,-0.582884,0.048072,0.648821,8.877742
V16,284807.0,1.437716e-15,0.876253,-14.129855,-0.468037,0.066413,0.523296,17.315112
V17,284807.0,-3.772171e-16,0.849337,-25.162799,-0.483748,-0.065676,0.399675,9.253526
V18,284807.0,9.564149e-16,0.838176,-9.498746,-0.498850,-0.003636,0.500807,5.041069
V19,284807.0,1.039917e-15,0.814041,-7.213527,-0.456299,0.003735,0.458949,5.591971
V20,284807.0,6.406204e-16,0.770925,-54.497720,-0.211721,-0.062481,0.133041,39.420904
V21,284807.0,1.654067e-16,0.734524,-34.830382,-0.228395,-0.029450,0.186377,27.202839
V22,284807.0,-3.568593e-16,0.725702,-10.933144,-0.542350,0.006782,0.528554,10.503090
V23,284807.0,2.578648e-16,0.624460,-44.807735,-0.161846,-0.011193,0.147642,22.528412
V24,284807.0,4.473266e-15,0.605647,-2.836627,-0.354586,0.040976,0.439527,4.584549
V25,284807.0,5.340915e-16,0.521278,-10.295397,-0.317145,0.016594,0.350716,7.519589
V26,284807.0,1.683437e-15,0.482227,-2.604551,-0.326984,-0.052139,0.240952,3.517346
V27,284807.0,-3.660091e-16,0.403632,-22.565679,-0.070840,0.001342,0.091045,31.612198
V28,284807.0,-1.227390e-16,0.330083,-15.430084,-0.052960,0.011244,0.078280,33.847808
Amount,284807.0,8.834962e+01,250.120109,0.000000,5.600000,22.000000,77.165000,25691.160000
Class,284807.0,1.727486e-03,0.041527,0.000000,0.000000,0.000000,0.000000,1.000000

In [6]:
df.shape

(284807, 31)

Finding the Target Output counts

Turns out the data is heavily UNDER SAMPLED

In [7]:
df.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [8]:
df.shape

(284807, 31)

Finding out the Null Values and Dropping them

In [9]:
df.isna()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
284803,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
284804,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
284805,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
284806,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [10]:
df.dropna(axis=0,inplace=True)

In [11]:
df.shape

(284807, 31)

Re-Sampling the data

In [12]:

X = df.drop('Class', axis=1)
y = df['Class']

smt = SMOTE()
X_resampled, y_resampled = smt.fit_resample(X, y)

In [13]:
X_resampled

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
0,0.000000,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.620000
1,0.000000,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.690000
2,1.000000,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.660000
3,1.000000,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.500000
4,2.000000,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.990000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
568625,93903.028258,-11.179062,7.093547,-13.442464,8.746204,-9.926152,-2.722137,-14.283781,4.367499,-5.980489,...,-0.140097,1.141444,-0.157296,0.321203,0.648974,-0.563920,-0.410567,-0.924160,-0.187704,32.803365
568626,93864.546107,-10.092688,6.882746,-15.669551,10.523409,-9.765738,-3.523046,-13.511467,7.031758,-5.370250,...,-0.550681,2.595563,-0.005194,-0.157600,0.475650,-0.768682,0.012757,-1.242012,-0.231366,20.577712
568627,123794.654698,-5.130048,4.257182,-7.974499,7.308013,-3.883425,-1.027481,-6.564919,3.521431,-4.951641,...,-0.467080,1.612745,0.981911,-0.227547,-0.119427,0.091817,0.509370,-0.984098,-1.000864,39.756608
568628,127629.898506,0.143212,1.558015,-4.268338,2.005629,-0.278515,-1.133697,-2.024944,0.571061,-1.327553,...,0.185565,0.405780,0.173686,-0.280737,0.350710,0.564883,0.133229,0.354338,0.228872,51.877241
568629,91562.466733,1.747393,1.753238,-4.464504,2.421892,1.934339,-1.649374,0.473907,-0.105846,1.078525,...,-0.219666,-0.386371,-0.831133,-0.030769,-0.041943,0.290919,-0.556761,0.039414,0.090478,2.151293

In [14]:
y_resampled

0         0
1         0
2         0
3         0
4         0
         ..
568625    1
568626    1
568627    1
568628    1
568629    1
Name: Class, Length: 568630, dtype: int64

In [15]:
y_resampled=pd.DataFrame(y_resampled)

In [16]:
y_resampled

        Class
0           0
1           0
2           0
3           0
4           0
...       ...
568625      1
568626      1
568627      1
568628      1
568629      1

[568630 rows x 1 columns]

Re-Sampling successful through OVERSAMPLING technique

In [17]:
y_resampled.value_counts()

Class
0        284315
1        284315
dtype: int64

Scaling the data into a normalized form, using MIN ABS scaler function because we need values in range of -1 to 1

In [18]:
scaled=MaxAbsScaler()

In [19]:
X_scaled=scaled.fit_transform(X_resampled)

In [20]:
Scaled_df=pd.DataFrame(X_scaled,columns=['Time','V1','V2','V3','V4','V5','V6','V7','V8','V9','V10','V11','V12','V13','V14','V15','V16','V17',
                       'V18','V19','V20','V21','V22','V23','V24','V25','V26','V27','V28','V29'])

Scaling successful hence proved by Statistical Measure of Data

In [21]:
Scaled_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Time,568630.0,0.508034,0.278676,0.000000,0.265968,0.464570,0.779390,1.000000
V1,568630.0,-0.043869,0.096591,-1.000000,-0.054065,-0.014522,0.014545,0.043521
V2,568630.0,0.026295,0.049939,-1.000000,-0.001354,0.013978,0.039838,0.303342
V3,568630.0,-0.075462,0.127343,-1.000000,-0.108310,-0.032030,0.005551,0.194153
V4,568630.0,0.137970,0.186352,-0.336774,-0.003301,0.087990,0.257646,1.000000
V5,568630.0,-0.014284,0.036318,-1.000000,-0.016041,-0.003902,0.003770,0.305967
V6,568630.0,-0.009786,0.023246,-0.356888,-0.021191,-0.009460,0.000326,1.000000
V7,568630.0,-0.024244,0.047298,-0.361203,-0.026897,-0.006235,0.001549,1.000000
V8,568630.0,0.003736,0.067419,-1.000000,-0.002699,0.002295,0.011651,0.273260
V9,568630.0,-0.085351,0.142715,-0.861434,-0.149184,-0.051922,0.005076,1.000000
V10,568630.0,-0.118019,0.179203,-1.000000,-0.186414,-0.043001,-0.001628,0.965710
V11,568630.0,0.161069,0.224998,-0.399160,-0.009924,0.100175,0.297110,1.000000
V12,568630.0,-0.170685,0.240801,-1.000000,-0.294888,-0.063816,0.008931,0.420066
V13,568630.0,-0.006567,0.139944,-0.812681,-0.103553,-0.004663,0.087243,1.000000
V14,568630.0,-0.185489,0.236294,-1.000000,-0.352759,-0.068693,0.003979,0.547860
V15,568630.0,-0.005808,0.103867,-0.506767,-0.064374,-0.001248,0.066102,1.000000
V16,568630.0,-0.121446,0.193941,-0.816042,-0.206166,-0.042783,0.012584,1.000000
V17,568630.0,-0.134867,0.228400,-1.000000,-0.220240,-0.025062,0.005969,0.367746
V18,568630.0,-0.120388,0.243139,-1.000000,-0.194916,-0.043586,0.031361,0.530709
V19,568630.0,0.047794,0.162720,-1.000000,-0.051824,0.031425,0.132051,0.775206
V20,568630.0,0.003408,0.018920,-1.000000,-0.003452,0.000741,0.008010,0.723350
V21,568630.0,0.011331,0.081433,-1.000000,-0.004544,0.004629,0.018613,0.781009
V22,568630.0,-0.000803,0.106242,-1.000000,-0.045755,0.001922,0.048231,0.960665
V23,568630.0,-0.000109,0.022748,-1.000000,-0.004986,-0.000592,0.004212,0.502780
V24,568630.0,-0.012182,0.117929,-0.618736,-0.084226,-0.001855,0.074040,1.000000
V25,568630.0,0.002542,0.059616,-1.000000,-0.029423,0.004386,0.035720,0.730384
V26,568630.0,0.008188,0.127503,-0.740488,-0.075838,-0.001791,0.087551,1.000000
V27,568630.0,0.002576,0.030121,-0.713828,-0.002131,0.001850,0.013727,1.000000
V28,568630.0,0.001219,0.012397,-0.455867,-0.001690,0.001091,0.006339,1.000000
V29,568630.0,0.003736,0.008590,0.000000,0.000131,0.000973,0.003892,1.000000

In [23]:
Scaled_df['Target']=y_resampled

In [24]:
Scaled_df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,V29,Target
0,0.000000,-0.024107,-0.001001,0.052485,0.081667,-0.002974,0.006308,0.001987,0.001348,0.023327,...,-0.000526,0.025412,-0.002466,0.014599,0.012485,-0.053766,0.004225,-0.000622,0.005824,0
1,0.000000,0.021129,0.003660,0.003445,0.026557,0.000528,-0.001124,-0.000653,0.001162,-0.016379,...,-0.006482,-0.058416,0.002261,-0.074129,0.016237,0.035792,-0.000284,0.000435,0.000105,0
2,0.000006,-0.024081,-0.018430,0.036693,0.022505,-0.004424,0.024563,0.006563,0.003383,-0.097124,...,0.007120,0.070582,0.020296,-0.150349,-0.031824,-0.039546,-0.001751,-0.001765,0.014739,0
3,0.000006,-0.017130,-0.002547,0.037102,-0.051157,-0.000091,0.017015,0.001970,0.005155,-0.088940,...,-0.003109,0.000482,-0.004247,-0.256421,0.062880,-0.063096,0.001984,0.001816,0.004807,0
4,0.000012,-0.020533,0.012071,0.032048,0.023883,-0.003580,0.001309,0.004917,-0.003695,0.052436,...,-0.000271,0.073015,-0.003068,0.030814,-0.020010,0.142804,0.006941,0.006356,0.002724,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
568625,0.543445,-0.198184,0.097552,-0.278165,0.518283,-0.087268,-0.037136,-0.118450,0.059652,-0.383488,...,0.032772,-0.014387,0.007168,0.141557,-0.054774,-0.116727,-0.029234,-0.005546,0.001277,1
568626,0.543223,-0.178925,0.094653,-0.324250,0.623597,-0.085858,-0.048062,-0.112045,0.096040,-0.344357,...,0.074520,-0.000475,-0.003517,0.103751,-0.074663,0.003627,-0.039289,-0.006835,0.000801,1
568627,0.716437,-0.090946,0.058546,-0.165016,0.433059,-0.034142,-0.014017,-0.054440,0.048096,-0.317515,...,0.046303,0.089811,-0.005078,-0.026050,0.008918,0.144817,-0.031130,-0.029570,0.001547,1
568628,0.738633,0.002539,0.021426,-0.088325,0.118850,-0.002449,-0.015466,-0.016792,0.007800,-0.085127,...,0.011650,0.015886,-0.006265,0.076498,0.054868,0.037878,0.011209,0.006762,0.002019,1
568629,0.529900,0.030978,0.024111,-0.092384,0.143517,0.017006,-0.022501,0.003930,-0.001446,0.069158,...,-0.011093,-0.076020,-0.000687,-0.009149,0.028257,-0.158290,0.001247,0.002673,0.000084,1

Data Sanitization and Engineering complete, saving the file into a new file named Feature_File.csv for Predictive Modelling.

In [25]:
Scaled_df.to_csv('Feature_file.csv')